const loginPage = document.querySelector('.login-page')
const registerPage = document.querySelector('.register-page')
const homePage = document.querySelector('.home-page')
const passwordPage = document.querySelector('.password-page')
const notesPage = document.querySelector('.notes-page')
const updatePage = document.querySelector('.update-container')
const homeFooter = document.querySelector('.botcontainer')

const loginForm = loginPage.querySelector('.form')
const registerForm = registerPage.querySelector('.form')
const updateForm = homePage.querySelector('.update-form')

const resetLink = loginPage.querySelector('.forgetpass')
const registerLink = loginPage.querySelector('.anchor')
const loginLink = registerPage.querySelector('.anchor')

const menuButton = document.querySelector('.burger')
const menuOptions = document.querySelector('.menu-options')
const closeButton = document.querySelector('.close')
const profileButton = document.querySelector('.profile-button')
const logoutButton = document.querySelector('.logout-button')
const homeButton = document.querySelector('.home-button')
const addNote = homePage.querySelector('.addnote')